// client/src/pages/activetrips.tsx
import React from 'react';
import Sidebar from './sidebar';

interface ActiveTripsProps {
  children: React.ReactNode;
}

const ActiveTrips: React.FC<ActiveTripsProps> = ({ children }) => {
  return (
    <div className="active-trips" style={{ display: 'flex' }}>
      <Sidebar />
      <main className="content" style={{ flex: 1, padding: '20px' }}>
        <h1 className="title" style={{ fontSize: '24px', marginBottom: '20px' }}>Active Trips</h1>
        {children}
      </main>
    </div>
  );
};

export default ActiveTrips;

// client/src/components/ActiveTrips.vue
<template>
    <div class="active-trips">
      <Sidebar />
      <main class="content">
        <h1 class="title">Active Trips</h1>
        <slot></slot>
      </main>
    </div>
  </template>
  
  <script>
  import Sidebar from './SideBar.vue'
  
  export default {
    name: 'ActiveTrips',
    components: {
      Sidebar
    }
  }
  </script>
  
  <style scoped>
  .active-trips {
    display: flex;
  }
  
  .content {
    flex: 1;
    padding: 20px;
  }
  
  .title {
    font-size: 24px;
    margin-bottom: 20px;
  }
  </style>
